### ISSUE TITLE
CSS reset

### ISSUE THREAD

**Issue by Nerone95** [ampproject/wg-amp4email#13]
Is it possible to enable some CSS reset?
Like:
-webkit-tap-highlight-color:transparent;

To disable the blue color on click on gmail android/ios:
![Screenshot_20191224-084517_Gmail](https://user-images.githubusercontent.com/51479683/71402112-508c2600-262c-11ea-9281-eab6202ae875.jpg)

And:
-webkit-appearance:none;
to remove on gmail  iOS:
![image](https://user-images.githubusercontent.com/51479683/71402179-84ffe200-262c-11ea-9e63-0c741935017a.png)

**Comment by fstanis** [comment]
We discussed this in January's meeting and decided to allow these, so both `-webkit-tap-highlight-color` and `-webkit-appearance` should now be supported in Gmail.

**Comment by Nerone95** [comment]
Great! Thank you for your support and attention!
