### ISSUE TITLE
AMP for email is working in playground but fails in gmail

### ISSUE THREAD

**Issue by Sharan-kumar** [ampproject/wg-amp4email#15]
i made a AMP html template in playground and tested in the same site it was working fine(even with proxy assertion token enabled state), but the same was failing in gmail with error message
in the console

**Error proxying amp-list templates with status:  404​​​**

here is the response headers for mail.google.com site configured in my server

**Access-Control-Allow-Origin : 'https://mail.google.com'
AMP-Access-Control-Allow-Source-Origin : 'amp@gmail.dev'
Access-Control-Expose-Headers : 'Access-Control-Allow-Origin,AMP-Access-Control-Allow-Source-Origin'
Access-Control-Allow-Headers : 'amp4email-proxy-assertion'**

PS: it will be better if there is a detailed error message in the console to debug, instead of just showing 404

**Comment by srikanthvvgs** [comment]
how is the issue resolved?

**Comment by Sharan-kumar** [comment]
The domain I was using was not visible to external networks, that's why google servers cannot make a http request to my domain, thus causing the 404 error, i solved it by making my domain visible to external networks
