### ISSUE TITLE
API not working in amp4email playground 

### ISSUE THREAD

**Issue by nareshjangidcn** [ampproject/wg-amp4email#25]

**Comment by zhangsu** [comment]
Could you clarify exactly what API is not working? Do you have the min repro AMP HTML?

**Comment by nareshjangidcn** [comment]
I am receiving the below error white sending email through "https://amp.gmail.dev/playground/":

Failed to fetch JSON data: XHR Failed fetching (https://m.snapdeal.com/...): Request viewerRenderTemplate failed: Error: Class$obf_1008: Access to fetch at 'https://m.snapdeal.com/...' from source origin 'cxe-reports@snapdeal.com' has been blocked by AMP CORS policy: The 'Access-Control-Expose-Headers' header has a value 'server-time,exe-time,xc,xg' that doesn't contain 'AMP-Access-Control-Allow-Source-Origin'.

**Comment by zhangsu** [comment]
It looks like you are using AMP CORS version 1, which is documented [here](https://amp.dev/documentation/guides-and-tutorials/learn/cors-in-email/#version-1-(deprecated)). As the error message says, the `Access-Control-Expose-Headers` header currently has a value `server-time,exe-time,xc,xg`. You need to add 'AMP-Access-Control-Allow-Source-Origin' to the list of exposed headers.

**Comment by nareshjangidcn** [comment]
Thank you @zhangsu. I will try after adding this variable.
