### ISSUE TITLE
Google AMP limitations for AMP emails

### ISSUE THREAD

**Issue by Thaddeusvasai** [ampproject/wg-amp4email#27]
Which Google AMP components can't be used in AMP mails but only in AMP webpages? Where can I find a list of these components?

**Comment by zhangsu** [comment]
https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components/?format=email

**Comment by Thaddeusvasai** [comment]
Thanks, Zhanhsu. Yes, there's an extensive list here of which components ARE supported. I've been told there are many AMP components that CAN'T be/AREN'T supported. Is there a list of those components that CAN'T be/AREN'T supported in AMP emails? I thought all amp components are supported for AMP emails but one has to do the coding correctly.

**Comment by zhangsu** [comment]
Any component in the non-email AMP format that is not in the email format is not supported in AMP emails. Here's the component list for AMP for Website, for example:

https://amp.dev/documentation/components/?format=websites
