### ISSUE TITLE
[Support Requested] No response from whitelisting application

### ISSUE THREAD

**Issue by SohamGovande** [ampproject/wg-amp4email#29]
Hi AMP team,

I hope you're doing well! I applied for AMP approval from Gmail for the email address adraful@tryfresco.dev more than a week ago but have not heard back yet. The [AMP Gmail docs](https://developers.google.com/gmail/ampemail/register) mention that the Gmail team tries to get to all requests within 5 working days so I wanted to follow up and ask about the status of my application. When can I expect to hear back?

Thanks!

**Comment by dmamie** [comment]
@SohamGovande have you heard back by now? if so, how long did it take?
