### ISSUE TITLE
Discussion: To Allow autoplay and delay in amp-carousel in AMP for Email

### ISSUE THREAD

**Issue by mcmd** [ampproject/wg-amp4email#6]
Currently, these two attributes are not allowed in AMP for Email.

If these were available, the fact that carousels are actually there could be highlighted. With these AMP components being such a new concept in email, we could see many users not recognizing that the carousel functionality is there and able to be interacted with. 

These feature could also help balancing the exposure of elements in different positions of a carousel in an email.

Could this be added to the spec?

**Comment by zhangsu** [comment]
We discussed this with the AMP for Email working group today, and everyone agreed that we can allow `autoplay` and `delay` for `amp-carousel`. I will take the action item to whitelist these two attributes in the spec.

**Comment by zhangsu** [comment]
This is done in https://github.com/ampproject/amphtml/pull/23384/files

@fstanis Can we close this issue now? (Apparently I don't have access to close issues)
